FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.api.txt ./requirements.api.txt
RUN pip install --no-cache-dir -r requirements.api.txt

COPY . .

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "demoAPI.main:app", "--host", "0.0.0.0", "--port", "8000"]
